# Generated by Django 4.2.5 on 2023-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
