# Generated by Django 4.2.5 on 2023-11-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('favorites', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='series',
            field=models.ManyToManyField(to='series.seriesvideo'),
        ),
    ]
