# Generated by Django 4.2.5 on 2023-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='horizontal_poster',
            field=models.ImageField(blank=True, null=True, upload_to='horizontal-poster', verbose_name='горизонтальный постер'),
        ),
    ]
