# Generated by Django 4.2.5 on 2023-11-27 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_horizontal_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AddField(
            model_name='seriesvideo',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
