# Generated by Django 4.2.5 on 2023-11-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_limit',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
