# Generated by Django 4.2.5 on 2023-11-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментария', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='commentseries',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментария для сериала', 'verbose_name_plural': 'Коментарии для сериалов'},
        ),
    ]
