# Generated by Django 4.2.5 on 2023-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_notification_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'movie'), (2, 'series'), (3, 'season'), (4, 'series_video'), (5, 'other'), (6, 'subscription')]),
        ),
    ]
