# Generated by Django 4.2.5 on 2023-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
    ]
