# Generated by Django 4.2.5 on 2023-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
